# Generated by Django 4.0.3 on 2022-10-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='commenti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
