# Generated by Django 4.0.3 on 2022-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_alter_humanresource_commenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresource',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='humanresource',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='operator_pictures/'),
        ),
    ]
