# Generated by Django 4.0.3 on 2022-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='id',
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='id_supplier',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
