# Generated by Django 4.0.3 on 2022-04-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_suppliers_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='category',
        ),
    ]
