# Generated by Django 4.0.3 on 2022-04-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_suppliers_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplierscategories'),
        ),
    ]
