# Generated by Django 4.0.3 on 2022-05-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0014_alter_suppliers_vat_perc_customerscontacts_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id_chemicals', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('cov', models.IntegerField(default=0)),
                ('tanning', models.BooleanField(default=False)),
                ('finishing', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('flamability_status', models.IntegerField(choices=[(1, 'A - LIQUIDI MOLTO INFIAMMABILI'), (2, 'B - LIQUIDI INFIAMMABILI'), (3, 'C - LIQUIDI COMBUSTIBILI'), (4, 'NON INFIAMMABILI')], default=4)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.suppliers')),
            ],
        ),
    ]
