# Generated by Django 4.0.3 on 2022-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('department', models.IntegerField(choices=[(1, 'Bagnato'), (2, 'Rifinizione')], default=1)),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
            },
        ),
        migrations.CreateModel(
            name='PrecautionaryStatements',
            fields=[
                ('id_ps', models.AutoField(primary_key=True, serialize=False)),
                ('ps_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'precautionary statement',
                'verbose_name_plural': 'precautionary statements',
            },
        ),
        migrations.CreateModel(
            name='Svhc',
            fields=[
                ('id_svhc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('numEc', models.CharField(blank=True, max_length=50, null=True)),
                ('numCas', models.CharField(blank=True, max_length=50, null=True)),
                ('inclusionDate', models.DateField(blank=True, null=True)),
                ('inclusionReason', models.TextField()),
                ('numDecision', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'svhc',
                'verbose_name_plural': 'svhc substances',
            },
        ),
        migrations.AlterModelOptions(
            name='chemicals',
            options={'verbose_name': 'chemical', 'verbose_name_plural': 'chemicals'},
        ),
    ]
