# Generated by Django 4.0.3 on 2022-05-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_operations_precautionarystatements_svhc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalsPackagingType',
            fields=[
                ('id_packaging_type', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('kg', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardStatements',
            fields=[
                ('id_hs', models.AutoField(primary_key=True, serialize=False)),
                ('hs_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('forbidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'hazard statement',
                'verbose_name_plural': 'hazard statements',
            },
        ),
        migrations.RenameField(
            model_name='chemicals',
            old_name='id_chemicals',
            new_name='id_chemical',
        ),
        migrations.CreateModel(
            name='ForbiddenHazStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.hazardstatements')),
            ],
        ),
    ]
