# Generated by Django 4.0.3 on 2022-05-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_chemicalspackagingtype_hazardstatements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalsPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
                ('id_packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicalspackagingtype')),
            ],
        ),
    ]
