# Generated by Django 4.0.3 on 2022-05-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0004_chemicalspackaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalHazardStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
                ('id_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.hazardstatements')),
            ],
        ),
        migrations.CreateModel(
            name='RegReach',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_name', models.CharField(max_length=50)),
                ('validity', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sds',
            fields=[
                ('id_sds', models.AutoField(primary_key=True, serialize=False)),
                ('sds', models.CharField(max_length=255)),
                ('rev_date', models.DateField()),
                ('conformityReach', models.BooleanField(default=True)),
                ('id_chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.regreach')),
            ],
        ),
        migrations.DeleteModel(
            name='ForbiddenHazStat',
        ),
        migrations.AddField(
            model_name='chemicalhazardstatements',
            name='id_sds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.sds'),
        ),
    ]
