# Generated by Django 4.0.3 on 2022-05-26 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0006_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
