# Generated by Django 4.0.3 on 2022-05-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0007_alter_prices_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='id_chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezzo', to='chemicals.chemicals'),
        ),
    ]
