# Generated by Django 4.0.3 on 2022-05-31 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0008_alter_prices_id_chemical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
