# Generated by Django 4.0.3 on 2022-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0009_alter_prices_price_alter_prices_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='cov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
