# Generated by Django 4.0.3 on 2022-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0013_alter_sds_rev_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds',
            name='sds',
            field=models.FileField(upload_to='sds'),
        ),
    ]
