# Generated by Django 4.0.3 on 2022-06-15 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_suppliers_vat_perc_customerscontacts_customers'),
        ('chemicals', '0015_alter_chemicaldangersymbols_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalOrder',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('n_order', models.IntegerField()),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField()),
                ('user_id', models.IntegerField()),
                ('conformity', models.BooleanField()),
                ('n_conformity', models.BooleanField()),
                ('n_conformity_reasons', models.TextField()),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('id_dich_int', models.IntegerField(blank=True, null=True)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.suppliers')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ChemicalOrderDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('um', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicalorder')),
                ('id_packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemicals.chemicalspackagingtype')),
            ],
        ),
    ]
