# Generated by Django 4.0.3 on 2022-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0017_alter_chemicalorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalorderdetail',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
