# Generated by Django 4.0.3 on 2022-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0018_alter_chemicalorderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
