# Generated by Django 4.0.3 on 2022-07-05 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0019_alter_chemicals_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
