# Generated by Django 4.0.3 on 2022-07-10 20:19

import chemicals.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0021_alter_prices_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalorder',
            name='n_order',
            field=models.PositiveIntegerField(default=chemicals.models.get_max_order_number),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
