# Generated by Django 4.0.3 on 2022-08-30 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_suppliers_vat_perc_customerscontacts_customers'),
        ('chemicals', '0022_alter_chemicalorder_n_order_alter_prices_price_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalPurchase',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('n_document', models.CharField(max_length=15)),
                ('date_doc', models.DateField(blank=True, null=True)),
                ('id_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.suppliers')),
            ],
            options={
                'verbose_name': 'Chemicals Purchase',
                'verbose_name_plural': 'Chemicals Purchases',
            },
        ),
        migrations.AlterModelOptions(
            name='substances',
            options={'verbose_name': 'Substance', 'verbose_name_plural': 'Substances'},
        ),
        migrations.AlterModelManagers(
            name='prices',
            managers=[
                ('chemicalprices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='chemicalorder',
            name='n_conformity_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sds',
            name='id_chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds', to='chemicals.chemicals'),
        ),
        migrations.CreateModel(
            name='ChemicalPurchaseDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('cov', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('id_chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicals')),
                ('id_purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemicalpurchase')),
            ],
        ),
    ]
